# Generated by Django 4.0.2 on 2022-06-26 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_minhotecauser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minhotecauser',
            name='address_complement',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='minhotecauser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
